parameters:
  stage_name: ""
  service_name: ""
  template_repo: ""
  feature_files_path: ""
  system_design_path: ""
  exclude_tags: "[]"
  dependsOn: []

# Description:

# The "Check traceability between URS and DS" should be generalised to something like "Integrity check",
# since it includes more that just traceability.
#E.g. it verifies that each @URS has a unique ID, scenarios not tagged @Manual or @ReviewByException in fact has step implementations, et cetera.

stages:
  - stage: ${{ parameters.stage_name }}
    variables:
      script_location: qms-pipeline-templates/templates/scripts/check_traceability_between_urs_ds.py
      dependency_location: qms-pipeline-templates/templates/scripts
    jobs:
      - job: Check_Traceability_between_URS_DS_job
        strategy:
          matrix:
            Python310:
              python.version: '3.8'
        # environment: "check_traceability_between_urs_ds"
        steps:
          - checkout: self
          - checkout: ${{parameters.template_repo}}

          - script: |
              set -e
              python3 -m pip install git+https://github.com/behave/behave
              python3 ${{ variables.script_location }} $(Build.Repository.Name)/${{ parameters.feature_files_path }} $(Build.Repository.Name)/${{ parameters.system_design_path }} '${{ parameters.exclude_tags }}'
            displayName: Check traceability between URS and DS
