parameters:
  stage_name: ""
  service_name: ""
  template_repo: ""
  feature_files_path: ""
  system_design_path: ""
  exclude_tags: "[]"
  dependsOn: []

# Description:

# The "Check traceability between URS and DS" should be generalised to something like "Integrity check",
# since it includes more that just traceability.
#E.g. it verifies that each @URS has a unique ID, scenarios not tagged @Manual or @ReviewByException in fact has step implementations, et cetera.

stages:
  - stage: ${{ parameters.stage_name }}
    variables:
      script_location: qms-pipeline-templates/templates/scripts/check_traceability_between_urs_ds.py
      dependency_location: qms-pipeline-templates/templates/scripts
    jobs:
      - job: Check_Traceability_between_URS_DS_job
        strategy:
          matrix:
            Python312:
              python.version: '3.12'
        # environment: "check_traceability_between_urs_ds"
        steps:
          - checkout: self
          - checkout: ${{parameters.template_repo}}

          - script: |
              set -e
              echo
              pip --version
              echo
              wget https://bootstrap.pypa.io/get-pip.py | python3
              pip3 install behave 
              echo "python3 ${{ variables.script_location }} $(Build.Repository.Name)/${{ parameters.feature_files_path }} $(Build.Repository.Name)/${{ parameters.system_design_path }} '${{ parameters.exclude_tags }}'"
              python3 ${{ variables.script_location }} $(Build.Repository.Name)/${{ parameters.feature_files_path }} $(Build.Repository.Name)/${{ parameters.system_design_path }} '${{ parameters.exclude_tags }}'
            displayName: Check traceability between URS and DS
