parameters:
  - name: stage_name
    type: string  
  - name: template_repo
    type: string
  - name: feature_files_path
    type: string
  - name: dependsOn
    type: object
    default: []
# Description:

# This will check for any "@manual @PV" tags and pause the pipeline to perform manual PV


stages:
  - stage: ${{ parameters.stage_name }}
    dependsOn: ${{ parameters.dependsOn }}
    variables:
      script_location: ../qms-pipeline-templates/templates/scripts/manual_pv.sh
      dependency_location: qms-pipeline-templates/templates/scripts
    jobs:
      - job: check_manualPV_job
        steps:
          - checkout: self
            fetchDepth: 0
          - checkout: ${{parameters.template_repo}}
        
          - script: |
              cd $(Build.Repository.Name)
              SCRIPT_PATH=$(dirname $(readlink -e ${{variables.script_location}}))/manual_pv.sh
              chmod +x $SCRIPT_PATH
              manual_tag_files=$($SCRIPT_PATH ${{parameters.feature_files_path}}
              if [ ! -z "$manual_tag_files" ]; then
                echo "$manual_tag_files"
                echo "##vso[task.setvariable variable=status;isOutput=true]true"
              else
                echo "No new manual PV tags found!"
                echo "##vso[task.setvariable variable=status;isOutput=true]false"
              fi
            name: manualPV
            displayName: Check for manual PV
