parameters:
  - name: stage_name
    type: string  
  - name: template_repo
    type: string
  - name: feature_files_path
    type: string
  - name: dependsOn
    type: object
    default: []
# Description:

# This will check for any "@manual @PV" tags and pause the pipeline to perform manual PV


stages:
  - stage: ${{ parameters.stage_name }}
    dependsOn: ${{ parameters.dependsOn }}
    variables:
      script_location: ../qms-pipeline-templates/templates/scripts/manual_pv.sh
      dependency_location: qms-pipeline-templates/templates/scripts
    jobs:
      - job: check_manualPV_job
        steps:
          - checkout: self
            fetchDepth: 0
          - checkout: ${{parameters.template_repo}}
        
          - script: |
              cd $(Build.Repository.Name)
              SCRIPT_PATH=$(dirname $(readlink -e ${{variables.script_location}}))/manual_pv.sh
              chmod +x $SCRIPT_PATH
              instScript=$($SCRIPT_PATH ${{parameters.feature_files_path}}  | grep "instScript" | cut -d'=' -f 2)
              echo "##vso[task.setVariable variable=status;isOutput=true]$instScript"
              echo "Release has manual PV changes: $instScript"
            name: manualPV
            displayName: Check for manual PV
