parameters:
  - name: stage_name
    type: string

  - name: dependsOn
    type: object

  - name: folder
    type: string

stages:
  - stage: ${{ parameters.stage_name }}
    dependsOn: ${{ parameters.dependsOn }}
    jobs:
      - job: Check_against_compliance
        steps:
          - checkout: none

          - script: |
              echo "This step is currently not enabled."
              #cp -r /mnt/cache/$(Build.Repository.Name)_cache/$(Build.BuildId)/cdk.out .
            displayName: Restore caches
            workingDirectory: $(System.DefaultWorkingDirectory)

          - script: |
              pwd
              ls
            displayName: Run CFN-GUARD
      - job: Trigger_GitHub_Dispatch
        steps:
          - script: |
              curl -X POST \
                -H "Accept: application/vnd.github.everest-preview+json" \
                -H "Authorization: token $(GH_PAT)" \
                https://api.github.com/repos/bidma-nn/github-webhook-test/dispatches \
                -d '{"event_type": "custom-event", "client_payload": { "message": "Hello, World!", "SNYK_SECRET": $(SNYK_CLIENT_ID), "SNYK_CLIENT_ID": $(SNYK_CLIENT_ID), "Pipeline_Run": $(Build.BuildNumber), "SNYK_API": "https://api.eu.snyk.io"  }}'
            displayName: Trigger GitHub Repository Dispatch