parameters:
  - name: stage_name
    type: string

  - name: dependsOn
    type: object

  - name: folder
    type: string

# Description:

# Purpose:

# Expected output:
stages:
  - stage: ${{ parameters.stage_name }}
    dependsOn: ${{ parameters.dependsOn }}
    jobs:
      - job: Check_against_compliance

        steps:
          # TODO: Implement cfn guard, cfn-nag, static code analysis etc.
          - checkout: none

          - script: |
              cp -r /mnt/cache/$(Build.Repository.Name)_cache/$(Build.BuildId)/cdk.out .
            displayName: Restore caches
            workingDirectory: $(System.DefaultWorkingDirectory)

          - script: |
              assets=($(ls -d cdk.out/asset.*))
              echo $assets
              zip -r veracode.zip $assets
            displayName: Setup environment

          - task: Veracode@3
            inputs:
              ConnectionDetailsSelection: 'Service Connection'
              AnalysisService: 'Veracode'
              veracodeAppProfile: '$(system.teamProject)'
              version: '$(build.buildNumber)'
              filepath: 'veracode.zip'
              importResults: true
              failBuildOnPolicyFail: true
              maximumWaitTime: '360'


          - script: |
              pwd
              ls
            displayName:
              Run CFN-GUARD
              # cfn-guard validate --data cdk.out --rules /${INPUT_RULE_SET_NAME}.guard --show-summary fail -p

          - publish: $(System.DefaultWorkingDirectory)/cdk.out
            artifact: cdk.out
            displayName: publish cdk.out
