parameters:
  - name: stage_name
    type: string

  - name: dependsOn
    type: object

  - name: folder
    type: string

resources:
  repositories:
    - repository: security_check
      type: github
      name: NovoNordisk-OpenSource/security_check
      endpoint: GH_public_service_connection
      ref: refs/heads/mpwk-snyk

stages:
  - stage: ${{ parameters.stage_name }}
    dependsOn: ${{ parameters.dependsOn }}
    jobs:
      - job: Check_against_compliance
        steps:
          - checkout: none

          - script: |
              echo "This step is currently not enabled."
              #cp -r /mnt/cache/$(Build.Repository.Name)_cache/$(Build.BuildId)/cdk.out .
            displayName: Restore caches
            workingDirectory: $(System.DefaultWorkingDirectory)

          - script: |
              pwd
              ls
            displayName: Run CFN-GUARD
      
  - template: security_check/action.yml@security_check
    parameters:
      SNYK_SECRET: $(SNYK_SECRET)
      SNYK_CLIENT_ID: $(SNYK_CLIENT_ID)
      Pipeline_Run: $(Build.BuildNumber)
