parameters:
  - name: stage_name
    type: string

  - name: dependsOn
    type: object

  - name: folder
    type: string

stages:
  - stage: ${{ parameters.stage_name }}
    dependsOn: ${{ parameters.dependsOn }}
    jobs:
      - job: Check_against_compliance
        steps:
          - checkout: none

          - script: |
              echo "This step is currently not enabled."
              #cp -r /mnt/cache/$(Build.Repository.Name)_cache/$(Build.BuildId)/cdk.out .
            displayName: Restore caches
            workingDirectory: $(System.DefaultWorkingDirectory)

          - script: |
              pwd
              ls
            displayName: Run CFN-GUARD
      
      - job: Security_Check
        steps:
          - uses: NovoNordisk-OpenSource/security_check@mpwk-snyk
            with:
              SNYK_SECRET: $(secret.SNYK_SECRET)
              SNYK_CLIENT_ID: $(secret.SNYK_CLIENT_ID)
              Pipeline_Run: $(Build.BuildNumber)