parameters:
  stage_name: ""
  environment_name: ""
  it_solution_name: ""
  feature_files_path: ""
  system_design_path: ""
  system_configuration_path: ""
  template_repo: ""
  verification_report_template_location: ""
  render_configuration_specifications_py_location: ""
  render_design_specifications_py_location: ""
  render_json_test_result_py_location: ""
  render_replace_py_location: ""
  render_requirements_py_location: ""
  get_pull_request_id_py_location: ""
  ready_for: ""

# Description:

# Purpose:

# Expected output:
stages:
  - stage: ${{ parameters.stage_name }}
    condition: and(not(or(failed(), canceled())), contains(variables['Build.SourceBranch'], 'refs/heads/release/'))
    jobs:
      - job: generate_verification_report
        workspace:
          clean: all
        steps:
          - checkout: self
          - checkout: ${{ parameters.template_repo }}

          - download: current
            artifact: pv-json
            displayName: Download PV Allure json test results from artifact store

          - script: |
              rm -rf $(Pipeline.Workspace)/pv-json/html
              cd $(Pipeline.Workspace)/pv-json
              ls -l
            displayName: Remove HTML folder if it exists

          - script: |
              ls -la
              echo "template_repo:"
              echo ${{ parameters.template_repo }}
              echo "local branches:"
              git branch
              echo "remote branches:"
              git branch -r
              echo $COMMIT_HASH
              prId=$(poetry run python ${{ parameters.get_pull_request_id_py_location }} -commit $COMMIT_HASH -accesstoken USE_ENV_VARIABLE -organization novonordiskit -project $(System.TeamProject) -repository $(Build.Repository.Name) -result pull_request_id)
              echo $prId
              prClosedTimestamp=$(poetry run python ${{ parameters.get_pull_request_id_py_location }} -commit $COMMIT_HASH -accesstoken USE_ENV_VARIABLE -organization novonordiskit -project $(System.TeamProject) -repository $(Build.Repository.Name) -result pull_request_closed_timestamp)
              echo $prClosedTimestamp
              echo "---------------------------------"
              poetry run python ${{ parameters.get_pull_request_id_py_location }} -commit $COMMIT_HASH -accesstoken USE_ENV_VARIABLE -organization novonordiskit -project $(System.TeamProject) -repository $(Build.Repository.Name) -result work_items > workItemsHtml.html
              cat workItemsHtml.html
              poetry run python ${{ parameters.render_json_test_result_py_location }} -folder $(Pipeline.Workspace)/pv-json > testResultsHtml.html
              poetry run python ${{ parameters.render_replace_py_location }} -render ./testResultsHtml.html -template ${{ parameters.verification_report_template_location }} -placeholder "<var>TESTCASE_RESULTS</var>"
              poetry run python ${{ parameters.render_replace_py_location }} -render ./workItemsHtml.html -template ${{ parameters.verification_report_template_location }} -placeholder "<var>WORK_ITEM_LINKS</var>"
              poetry run python ${{ parameters.render_replace_py_location }} -render ./workItemsHtml.html -template ${{ parameters.verification_report_template_location }} -placeholder "<kbd><var>CHANGE_ITEM</var></kbd>"
              poetry run python ${{ parameters.render_requirements_py_location }} -folder ${{ parameters.feature_files_path }} > listOfRequirementsHtml.html
              poetry run python ${{ parameters.render_replace_py_location }} -render ./listOfRequirementsHtml.html -template ${{ parameters.verification_report_template_location }} -placeholder "<var>LIST_OF_REQUIREMENTS</var>"
              poetry run python ${{ parameters.render_design_specifications_py_location }} -folder ${{ parameters.system_design_path }} > listOfDesignSpecifications.html
              poetry run python ${{ parameters.render_replace_py_location }} -render ./listOfDesignSpecifications.html -template ${{ parameters.verification_report_template_location }} -placeholder "<var>LIST_OF_DESIGN_SPECIFICATIONS</var>"
              poetry run python ${{ parameters.render_configuration_specifications_py_location }} -folder ${{ parameters.system_configuration_path }} > listOfConfigurationSpecifications.html
              poetry run python ${{ parameters.render_replace_py_location }} -render ./listOfConfigurationSpecifications.html -template ${{ parameters.verification_report_template_location }} -placeholder "<var>LIST_OF_CONFIGURATION_SPECIFICATIONS</var>"
              sed -i 's|<var>IT_SOLUTION_NAME</var>|${{ parameters.it_solution_name }}|g' ${{ parameters.verification_report_template_location }}
              sed -i 's|<var>PIPELINE_RUN_ID</var>|$(Build.BuildId)|g' ${{ parameters.verification_report_template_location }}
              sed -i "s|<var>TIMESTAMP_PIPELINE_START</var>|$prClosedTimestamp|g" ${{ parameters.verification_report_template_location }}
              sed -i 's|<var>ENVIRONMENT</var>|${{ parameters.environment_name }}|g' ${{ parameters.verification_report_template_location }}
              sed -i 's|<var>ADO_PROJECT_NAME</var>|$(System.TeamProject)|g' ${{ parameters.verification_report_template_location }}
              sed -i 's|<var>IS_READY_FOR</var>|${{ parameters.ready_for }}|g' ${{ parameters.verification_report_template_location }}
              sed -i "s|<var>PULL_REQUEST_LINK</var>|$(System.CollectionUri)$(System.TeamProject)/_git/$(Build.Repository.Name)/pullrequest/$prId|g" ${{ parameters.verification_report_template_location }}
              sed -i 's|<var>ADO_PIPELINE_RUN_LINK</var>|$(System.CollectionUri)$(System.TeamProject)/_build/results?buildId=$(Build.BuildId)\&view=results|g' ${{ parameters.verification_report_template_location }}
              sed -i 's|<var>ARTIFACTS_ADO_PIPELINE_LINK</var>|$(System.CollectionUri)$(System.TeamProject)/_build/results?buildId=$(Build.BuildId)\&view=artifacts\&pathAsName=false\&type=publishedArtifacts|g' ${{ parameters.verification_report_template_location }}
            env:
              SYSTEM_ACCESSTOKEN: $(System.AccessToken)
              COMMIT_HASH: $(Build.SourceVersion)
            workingDirectory: ${{ parameters.template_repo }}
            displayName: Generate verification report as HTML

          - publish: ${{ parameters.template_repo }}/${{ parameters.verification_report_template_location }}
            artifact: verification_report
            displayName: Publish verification report as build artifact

          
