parameters:
  stage_name: ""
  template_repo: ""
  operations_path: ""

# Description:

# Purpose:

# Expected output:
stages:
  - stage: ${{parameters.stage_name}}
    dependsOn: []
    variables:
      script_location: ../qms-pipeline-templates/templates/scripts/o_and_m.sh
    jobs:
      - job: o_and_m_check
        steps:
          - checkout: self
            fetchDepth: 0
          - checkout: ${{parameters.template_repo}}

          - script: |
              cd $(Build.Repository.Name)
              SCRIPT_PATH=$(dirname $(readlink -e ${{variables.script_location}}))/o_and_m.sh
              chmod +x $SCRIPT_PATH
              o_and_m_files=$($SCRIPT_PATH ${{parameters.operations_path}})
              if [ ! -z "$o_and_m_files" ]; then
                echo "$o_and_m_files"
                echo "##vso[task.setvariable variable=status;isOutput=true]true"
              else
                echo "No new changes to O&M docs!"
                echo "##vso[task.setvariable variable=status;isOutput=true]false"
              fi
            name: scripts
            displayName: Check for O&M Changes
