parameters:
  stage_name: ""
  template_repo: ""
  operations_path: ""

# Description:

# Purpose:

# Expected output:
stages:
  - stage: ${{parameters.stage_name}}
    dependsOn: []
    variables:
      check_install_script_location: qms-pipeline-templates/templates/scripts/o_and_m.sh
    jobs:
      - job: o_and_m_check
        steps:
          - checkout: self
          - checkout: ${{parameters.template_repo}}

          - script: |
              ls
              chmod 777 ${{variables.check_install_script_location}}
              ${{variables.check_install_script_location}} $(Build.Repository.Name)/${{parameters.operations_path}}
              instScript=$(${{variables.check_install_script_location}} $(Build.Repository.Name)/${{parameters.operations_path}}  | grep "instScript" | cut -d'=' -f 2)
              echo "##vso[task.setVariable variable=instScript;isOutput=true]$instScript"
              echo "Release has O&M changes: $instScript"
            name: scripts
