parameters:
  stage_name: ""
  template_repo: ""
  script_path: ""
  depends_on: []

# Description:

# Purpose:

# Expected output:
stages:
  - stage: ${{parameters.stage_name}}
    dependsOn: []
    variables:
      check_install_script_location: qms-pipeline-templates/templates/scripts/install_scripts.sh
    jobs:
      - job: installation_script_check
        steps:
          - checkout: self
          - checkout: ${{parameters.template_repo}}

          - script: |
              ls
              chmod 777 ${{variables.check_install_script_location}}
              ${{variables.check_install_script_location}} ${{parameters.script_path}}
              instScript=$(${{variables.check_install_script_location}} ${{parameters.script_path}}  | grep "instScript" | cut -d'=' -f 2)
              echo "##vso[task.setVariable variable=instScript;isOutput=true]$instScript"
              echo "Release has Installation Script changes: $instScript"
            name: scripts
