parameters:
  stage_name: ""
  template_repo: ""
  operations_path: ""

# Description:

# Purpose:

# Expected output:
stages:
  - stage: ${{parameters.stage_name}}
    dependsOn: []
    variables:
      script_location: qms-pipeline-templates/templates/scripts/o_and_m.sh
    jobs:
      - job: o_and_m_check
        steps:
          - checkout: self
            fetchDepth: 0
          - checkout: ${{parameters.template_repo}}

          - script: |
              cd $(Build.Repository.Name)
              SCRIPT_PATH=$(dirname $(readlink -e ${{variables.script_location}}))/o_and_m.sh
              chmod +x $SCRIPT_PATH
              instScript=$($SCRIPT_PATH ${{parameters.operations_path}}  | grep "instScript" | cut -d'=' -f 2)
              echo "##vso[task.setVariable variable=status;isOutput=true]$instScript"
              echo "Release has O&M changes: $instScript"
            name: scripts
