parameters:
  stage_name: ""
  template_repo: ""
  script_path: ""
  depends_on: []

# Description:

# Purpose:

# Expected output:
stages:
  - stage: ${{parameters.stage_name}}
    dependsOn: []
    variables:
      check_install_script_location: ../qms-pipeline-templates/templates/scripts/install_scripts.sh
    jobs:
      - job: installation_script_check
        steps:
          - checkout: self
            fetchDepth: 0
          - checkout: ${{parameters.template_repo}}

          - script: |

              cd $(Build.Repository.Name)
              SCRIPT_PATH=$(dirname $(readlink -e ${{variables.check_install_script_location}}))/install_scripts.sh
              chmod +x $SCRIPT_PATH
              instScript=$($SCRIPT_PATH ${{parameters.script_path}}  | grep "instScript" | cut -d'=' -f 2)
              echo "##vso[task.setVariable variable=instScript;isOutput=true]$instScript"
              echo "Release has Installation Script changes: $instScript"
            name: scripts
