parameters:
  - name: stage_name
    type: string

  - name: template_repo
    type: string

  - name: dependsOn
    type: object
    default: []
# Description:

# Purpose:

# Expected output:
stages:
  - stage: ${{ parameters.stage_name }}
    dependsOn: []
    condition: and(not(or(failed(), canceled())), contains(variables['Build.SourceBranch'], 'refs/heads/release/'))
    variables:
      dependency_location: templates/scripts
    jobs:
      - job: link_to_workitem
        steps:
          - checkout: ${{ parameters.template_repo }}

          - script: |
              echo
              pwd
              echo
              ls
              echo
              python3 -m ensurepip --upgrade
              pip3 install -r requirements.txt
              python3 templates/scripts/report/get_pull_request_id.py -commit $COMMIT_HASH -accesstoken USE_ENV_VARIABLE -organization novonordiskit -project '$(System.TeamProject)' -repository $(Build.Repository.Name) -result add_work_item_link
            displayName: Link to work item
            env:
              COMMIT_HASH: $(Build.SourceVersion)
              BUILD_ID: $(Build.BuildId)
              SYSTEM_ACCESSTOKEN: $(System.AccessToken)
