parameters:
  - name: stage_name
    type: string

  - name: template_repo
    type: string

  - name: dependsOn
    type: object
    default: []
# Description:

# Purpose:

# Expected output:
stages:
  - stage: ${{ parameters.stage_name }}
    dependsOn: []
    condition: and(not(or(failed(), canceled())), contains(variables['Build.SourceBranch'], 'refs/heads/release/'))
    variables:
      dependency_location: templates/scripts
    jobs:
      - job: link_to_workitem
        steps:
          - checkout: ${{ parameters.template_repo }}

          - script: |
              set -e
              echo "Fetching all work items attached to PR"
              echo ""
              script_return=$(python3 templates/scripts/report/get_pull_request_id.py -commit $COMMIT_HASH -accesstoken USE_ENV_VARIABLE -organization novonordiskit -project '$(System.TeamProject)' -repository $(Build.Repository.Name) -result work_item_list)
              echo "$script_return"
              echo ""
              echo "Fetching the work item tagged with IT Change"
              script_return=$(python3 templates/scripts/report/get_pull_request_id.py -commit $COMMIT_HASH -accesstoken USE_ENV_VARIABLE -organization novonordiskit -project '$(System.TeamProject)' -repository $(Build.Repository.Name) -result work_item_with_tag)
              echo "$script_return" 
              echo ""
            displayName: Link to work item
            env:
              COMMIT_HASH: $(Build.SourceVersion)
              BUILD_ID: $(Build.BuildId)
              SYSTEM_ACCESSTOKEN: $(System.AccessToken)
