parameters:
  - name: stage_name
    type: string

  - name: check_for_configuration_specifications_stage_name
    type: string

  - name: environment
    type: string

  - name: dependsOn
    type: object
# Description:

# Purpose:

# Expected output:
stages:
  - stage: ${{ parameters.stage_name }}
    condition: and(and(not(or(failed(), canceled())), eq(dependencies.${{ parameters.check_for_configuration_specifications_stage_name }}.outputs['installation_script_check.scripts.instScript'], 'true')), contains(variables['Build.SourceBranch'], 'refs/heads/release/')
    dependsOn: ${{ parameters.dependsOn }}
    jobs:
      - deployment: Execute_Installation_Script
        environment: ${{ parameters.environment }}
        strategy:
          runOnce:
            deploy:
              steps:
                - bash: echo "Please execute the scripts listed in the previous stage"



