parameters:
  - name: stage_name
    type: string

  - name: check_for_o_and_m_stage_name
    type: string

  - name: environment
    type: string

  - name: dependsOn
    type: object
# Description:

# Purpose:

# Expected output:
stages:
  - stage: ${{ parameters.stage_name }}
    condition: and(and(not(or(failed(), canceled())), eq(dependencies.${{ parameters.check_for_o_and_m_stage_name }}.outputs['o_and_m_check.scripts.status'], 'true')), contains(variables['Build.SourceBranch'], 'refs/heads/release/'))
    dependsOn: ${{ parameters.dependsOn }}
    jobs:
      - deployment: Check_Operations_Docs
        environment: ${{ parameters.environment }}
        strategy:
          runOnce:
            deploy:
              steps:
                - bash: echo "Please verify the O&M files listed in the previous stage"



